---
# evening routine
- alias: 'timer_evening_startevening'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    - service: hue.activate_scene
      target:
        entity_id:
          - scene.zitkamer_dom_evening
          - scene.eettafel_dom_default
          - scene.achtertuin_dom_outdoor_evening
          - scene.voortuin_dom_evening
    - service: light.turn_on
      entity_id:
        - light.hal_led_bak
        - light.kerstboom
    - service: switch.turn_on
      target:
        entity_id:
          - switch.shelly_christmas_outdoor

- alias: 'timer_evening_goodnight'
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_party
      state: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.h_schemerlamp
        - light.h_staande_lamp
        - light.h_tv_lamp
        - light.h_piano
        - light.hal_led_bak
        - light.h_outdoor_1
        - light.h_outdoor_2
        - light.h_outdoor_3
        - light.h_outdoor_4
        - light.h_outdoor_5
        - light.h_outdoor_6
        - light.h_outdoor_7
        - light.h_tafel_kamer
        - light.h_tafel_raam
        - light.h_tv_play_left
        - light.h_tv_play_right
        - light.kerstboom
    - service: switch.turn_off
      target:
        entity_id:
          - switch.shelly_christmas_outdoor

- alias: 'timer_evening_carport'
  trigger:
    platform: sun
    event: sunrise
    offset: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.h_carport

- alias: 'night_mode_carport_soft'
  trigger:
    platform: state
    entity_id: input_boolean.is_it_night
    to: 'on'
  condition:
    - condition: state
      entity_id: light.h_carport
      state: 'on'
  action:
    - service: hue.activate_scene
      target:
        entity_id: scene.voortuin_dom_night

- alias: 'day_mode_carport_hard'
  trigger:
    platform: state
    entity_id: input_boolean.is_it_night
    to: 'off'
  condition:
    - condition: state
      entity_id: light.h_carport
      state: 'on'
  action:
    - service: hue.activate_scene
      target:
        entity_id: scene.voortuin_dom_evening

