---
# morning routine
- alias: 'timer_morning_startmorning'
  trigger:
    - platform: state
      entity_id: schedule.morning_routine
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: state
      entity_id: input_boolean.is_it_weekend
      state: 'off'
  action:
    - service: hue.activate_scene
      target:
        entity_id: scene.woonkamer_dom_morning
    - service: switch.turn_on
      target:
        entity_id: switch.shellyplug_s_20e7b0 # christmas outdoor
    - service: light.turn_on
      entity_id: light.hal_led_bak

- alias: 'timer_morning_startradio'
  trigger:
    - platform: state
      entity_id: schedule.morning_routine
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: state
      entity_id: input_boolean.is_it_weekend
      state: 'off'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_badkamer
        - media_player.sonos_woonkamer
        - media_player.sonos_eetkamer
        - media_player.sonos_keuken
      data:
        volume_level: .05
    - service: media_player.play_media
      target:
        entity_id: media_player.sonos_badkamer
      data:
        media_content_type: "favorite_item_id"
        media_content_id: "FV:2/19" # Morning Wood favorite
    - service: media_player.shuffle_set
      entity_id: media_player.sonos_badkamer
      data:
        shuffle: true
    - service: media_player.media_next_track
      entity_id: media_player.sonos_badkamer
    - service: media_player.join
      target:
        entity_id: media_player.sonos_badkamer
      data:
        group_members:
          - media_player.sonos_keuken
          - media_player.sonos_woonkamer
          - media_player.sonos_eetkamer

- alias: 'timer_morning_everythingoff'
  trigger:
    - platform: state
      entity_id: schedule.morning_routine
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: state
      entity_id: input_boolean.is_it_weekend
      state: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.h_schemerlamp
        - light.h_staande_lamp
        - light.h_tv_lamp
        - light.h_piano
        - light.hal_led_bak
        - light.h_outdoor_1
        - light.h_outdoor_2
        - light.h_outdoor_3
        - light.h_outdoor_4
        - light.h_outdoor_5
        - light.h_outdoor_6
        - light.h_outdoor_7
        - light.h_christmas_tree
        - light.h_tafel_kamer
        - light.h_tafel_raam
        - light.h_tv_play_left
        - light.h_tv_play_right
    - service: switch.turn_off
      target:
        entity_id:
          - switch.shellyplug_s_20e7b0 # christmas outdoor
    - service: media_player.unjoin
      target:
        entity_id:
          - media_player.sonos_keuken
          - media_player.sonos_woonkamer
          - media_player.sonos_eetkamer
    - service: media_player.media_pause
      entity_id: media_player.sonos_badkamer

- alias: 'timer_morning_heating_on_noholiday'
  trigger:
    - platform: state
      entity_id: schedule.morning_heating
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: state
      entity_id: input_boolean.someone_home
      state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.anna
        preset_mode: 'home'

- alias: 'timer_morning_heating_on_holiday'
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'on'
    - condition: state
      entity_id: input_boolean.someone_home
      state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.anna
        preset_mode: 'home'
