---
- alias: "Play audio file for school end in 15 mins"
  trigger:
    - platform: state
      entity_id: schedule.school_end
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
  action:
    - service: notify.pushover
      data:
        title: "School uit"
        message: "Over een kwartier is de school uit!"
    - service: media_player.play_media
      target:
        entity_id:
          - media_player.sonos_woonkamer
          - media_player.sonos_eetkamer
          - media_player.sonos_keuken
          - media_player.sonos_kantoor
      data:
        announce: true
        media_content_id: "http://192.168.0.73:8123/local/school_uit.mp3"
        media_content_type: "music"
        extra:
          volume: 30
