---
- alias: Event doorbell
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.doorbell_ringing # Eufy
      to: 'on'
    - platform: state
      entity_id: input_boolean.fake_doorbell
      to: 'on'
  action:
    - service: camera.snapshot
      entity_id: camera.street
      data:
        filename: "/tmp/eventdoorbell1.jpg"
    - service: camera.snapshot
      entity_id: camera.frontdoor
      data:
        filename: "/tmp/eventdoorbell2.jpg"
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: -2
          attachment: "/tmp/eventdoorbell1.jpg"
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: 0
          attachment: "/tmp/eventdoorbell2.jpg"
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - file: "/tmp/eventdoorbell2.jpg"
              caption: "Deurbel gaat"
    - service: media_player.play_media
      target:
        entity_id:
          - media_player.sonos_keuken
          - media_player.sonos_badkamer
      data:
        announce: true
        media_content_id: "http://192.168.0.73:8123/local/doorbell.mp3"
        media_content_type: "music"
        extra:
          volume: 30
    - service: input_boolean.turn_off
      entity_id: input_boolean.fake_doorbell

- alias: TV Woonkamer pause doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_ringing
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.atv_living_room_4k
      state: 'playing'
  action:
    - service: media_player.media_pause
      target:
        entity_id: media_player.atv_living_room_4k
