---
# Woonkamer on
- alias: Woonkamer verlichting aan
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:11'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_11
    state: 'on'
  action:
    - service: hue.activate_scene
      target:
        entity_id: scene.zitkamer_dom_evening
    - service: light.turn_on
      data:
        entity_id: light.kerstboom

# Woonkamer off
- alias: Woonkamer verlichting uit
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:11'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_11
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_schemerlamp
        - light.h_staande_lamp
        - light.h_tv_lamp
        - light.h_piano
        - light.h_tv_play_left
        - light.h_tv_play_right
        - light.hal_led_bak
        - light.kerstboom

# Tafelverlichting on
- alias: Tafelverlichting aan
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:12'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_12
    state: 'on'
  action:
    service: hue.activate_scene
    target:
      entity_id: scene.eettafel_dom_default

# Tafelverlichting off
- alias: Tafelverlichting uit
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:12'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_12
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_tafel_kamer
        - light.h_tafel_raam


# Turn of outdoor christmas lights if livingroombutton off is pressed
- alias: Turn of outdoor christmas with button
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: hs_living_room_button
      type: short_release
  condition:
    condition: state
    entity_id: switch.shellyplug_s_20e7b0
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.shellyplug_s_20e7b0
 
