---
- alias: Car insurance expiration
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.volkswagen_r429fg_liability_insured
      to: 'off'
  action:
    - service: notify.pushover
      data_template:
        title: "Verzekering"
        message: "Verzekering van een auto verlopen."

- alias: APK upcoming VW
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.volkswagen_r429fg_apk_expiration
      below: 1
      value_template: "{{ (as_timestamp(states.sensor.volkswagen_r429fg_apk_expiration.state) - (as_timestamp(now() + timedelta(days=30)))) / (3600 * 24) }}"
  action:
    - service: notify.pushover
      data_template:
        title: "APK"
        message: "APK van VW Passat verloopt binnen 30 dagen."
