---
- alias: Front door opens
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_door_frontdoor_door_window
      to: 'on'
  action:
    - service: camera.snapshot
      entity_id: camera.frontdoor
      data:
        filename: "/tmp/frontdooropens.jpg"
    - service: notify.pushover
      data:
        title: "Voordeur geopend"
        message: "De voordeur is geopend"
        data:
          priority: -2
          attachment: "/tmp/frontdooropens.jpg"
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - file: '/tmp/frontdoormotion.jpg'
              caption: "De voordeur is geopend"

- alias: Front door person
  trigger:
    - platform: state
      entity_id:
        - sensor.doorbell_person_name
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - sensor.doorbell_person_name
          state: "unavailable"
        - condition: state
          entity_id:
            - sensor.doorbell_person_name
          state: ""
        - condition: state
          entity_id:
            - sensor.doorbell_person_name
          state: "Unknown"
  action:
    - service: notify.pushover
      data_template:
        title: "{{ trigger.to_state.state }} gedetecteerd"
        message: "{{ trigger.to_state.state }} is gedecteerd bij de voordeur"
    # - service: notify.telegram

- alias: Front door motion
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.doorbell_person_detected
      to: 'on'
    - platform: state
      entity_id: input_boolean.tts_test
      to: 'on'
  action:
    - service: camera.snapshot
      entity_id: camera.frontdoor
      data:
        filename: "/tmp/frontdoormotion.jpg"
    - service: notify.pushover
      data:
        title: "Persoon bij de voordeur"
        message: "Er is een persoon bij de voordeur gedetecteerd"
        data:
          attachment: "/tmp/frontdoormotion.jpg"
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - file: '/tmp/frontdoormotion.jpg'
              caption: "Persoon bij de voordeur"
    - service: input_boolean.turn_off
      entity_id: input_boolean.tts_test

- alias: Front door motion carport light
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_person_detected
      to: 'on'
    - platform: state
      entity_id:
        - binary_sensor.doorbell_global_motion_sensor
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.is_it_night
        state: 'on'
      - condition: state
        entity_id: light.h_carport
        state: 'on'
  action:
    - service: hue.activate_scene
      target:
        entity_id: scene.voortuin_dom_evening
    - delay: "00:01"
    - service: hue.activate_scene
      target:
        entity_id: scene.voortuin_dom_night

