---
- alias: Afval notificatie morgen
  trigger:
    - platform: time
      at: '19:15:00'
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.afvalwijzer_tomorrow', 'Geen') }}"
  action:
    - service: notify.pushover
      data_template:
        title: "Afval"
        message: "Morgen: {{ states.sensor.afvalwijzer_tomorrow.state }}"

- alias: Afval notificatie vandaag
  trigger:
    - platform: time
      at: '07:15:00'
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.afvalwijzer_today', 'Geen') }}"
  action:
    - service: notify.pushover
      data_template:
        title: "Afval"
        message: "Vandaag: {{ states.sensor.afvalwijzer_today.state }}"
