---
- alias: Weather morning notification
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service_template: notify.pushover
      data_template:
        title: "Weerbericht"
        message: "Het wordt vandaag
          min. {{ states.sensor.pirateweather_overnight_low_temperature_0d.state | round(0) }} en
          max. {{ states.sensor.pirateweather_daytime_high_temperature_0d.state | round(0) }} graden.
          Het is nu {{ states.sensor.pirateweather_temperature.state | round(0) }}
          graden."

- alias: Weather evening notification
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service_template: notify.pushover
      data_template:
        title: "Weerbericht"
        message: "Het wordt morgen
          min. {{ states.sensor.pirateweather_overnight_low_temperature_1d.state | round(0) }} en
          max. {{ states.sensor.pirateweather_daytime_high_temperature_1d.state | round(0) }} graden."

- alias: Open window notification
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.bedroom_vs_outdoor_temperature
      below: 0.0
      for:
        minutes: 1
  condition:
    or:
      - condition: state
        entity_id: binary_sensor.raam_alex_door
        state: 'on'
      - condition: state
        entity_id: binary_sensor.raam_emma_door
        state: 'on'
      - condition: state
        entity_id: binary_sensor.raam_slaapkamer_door
        state: 'on'
  action:
    - service_template: notify.pushover
      data_template:
        title: "Buiten warmer dan binnen en raam open"
        message: "Het is buiten {{ states.sensor.bedroom_vs_outside_temperature.state | float * -1 }}
          graden warmer dan binnen, ramen boven sluiten"
