---
- alias: Weather morning notification
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service_template: notify.pushover
      data_template:
        title: "Weerbericht"
        message: "Het wordt vandaag
          min. {{ states.sensor.dark_sky_overnight_low_temperature_0d.state | round(0) }} en
          max. {{ states.sensor.dark_sky_daytime_high_temperature_0d.state | round(0) }} graden.
          Het is nu {{ states.sensor.temperatuur_buiten_temperature.state | round(0) }}
          graden."
