---
- platform: switch
  name: Plafondlamp
  entity_id: switch.ac_07d3646_1
- platform: switch
  name: Hal - LED bak
  entity_id: switch.ac_0f70e12_2
- platform: switch
  name: Woonkamer
  entity_id: switch.livingroom_lighting
- platform: switch
  name: Tafel
  entity_id: switch.diningtable_lighting
- platform: switch
  name: Buiten
  entity_id: switch.outdoor_lighting
- platform: switch
  name: Badkamer
  entity_id: switch.bathroom_lighting
