---

# turn on airco, hot upstairs
- alias: turn on airco
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.temperatuur_slaapkamer
        - sensor.hm_emma_temperature
      above: 23.0
      for:
        minutes: 10
    - platform: state
      entity_id:
        - binary_sensor.deur_slaapkamer_door
        - binary_sensor.deur_emma_door
      to: 'on'
  condition:
    and:
      - condition: state
        entity_id: climate.overloop
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.hm_backyard_temperature
        above: 20.0
      - or:
        - and:
          - condition: numeric_state
            entity_id: sensor.hm_emma_temperature
            above: 23.0
          - condition: state
            entity_id: binary_sensor.deur_emma_door
            state: 'on'
        - and:
          - condition: numeric_state
            entity_id: sensor.temperatuur_slaapkamer
            above: 23.0
          - condition: state
            entity_id: binary_sensor.deur_slaapkamer_door
            state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.overloop
        temperature: 18.0
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.overloop
        hvac_mode: cool
    - service: climate.turn_on
      entity_id: climate.overloop
    - service: fan.turn_on
      data:
        percentage: 25
      target:
        entity_id: fan.smartmi_standing_fan_3
    - service: fan.oscillate
      target:
        entity_id: fan.smartmi_standing_fan_3
      data:
        oscillating: true
    - service: notify.pushover
      data_template:
        title: "Airco"
        message: "Airco gaat aan omdat er een kamer > 23.0 graden is."
        data:
          priority: -2

# turn off airco, cooled down upstairs
- alias: turn off airco
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.temperatuur_slaapkamer
      - sensor.hm_emma_temperature
    below: 22.7
    for:
      minutes: 20
  condition:
    and:
      - condition: state
        entity_id: climate.overloop
        state: 'cool'
      - condition: numeric_state
        entity_id: sensor.temperatuur_slaapkamer
        below: 22.7
      - condition: numeric_state
        entity_id: sensor.hm_emma_temperature
        below: 22.7
      - or:
        - condition: state
          entity_id: input_boolean.night_airco_on
          state: 'off'
        - and:
            - condition: state
              entity_id: input_boolean.night_airco_on
              state: 'on'
            - condition: state
              entity_id: input_boolean.is_it_night
              state: 'off'
  action:
    - service: climate.turn_off
      entity_id: climate.overloop
    - service: fan.turn_off
      target:
        entity_id: fan.smartmi_standing_fan_3
    - service: notify.pushover
      data_template:
        title: "Airco"
        message: "Airco gaat uit omdat alle kamers < 22.7 graden zijn."
        data:
          priority: -2

- alias: Left window/door open airco
  trigger:
    platform: state
    entity_id: climate.overloop
    to: 'cool'
  condition:
    - condition: state
      entity_id: group.airco_windows
      state: 'on'
  action:
    - service: notify.pushover
      data_template:
        message: >-
          {%- for entity in states.group.airco_windows.attributes.entity_id -%}
            {%- if states[entity.split('.')[0]][entity.split('.')[1]].state
              == 'on' %}
              {{ states[entity.split('.')[0]][entity.split('.')[1]]
                .attributes.friendly_name }}
            {%- endif %}
          {%- endfor -%}
        title: "Airco gaat aan, raam nog open: "
        data:
          priority: 1

# TODO: shut down airco if doors closed upstairs

- alias: Nachtairco modus aan
  trigger:
    platform: state
    entity_id: input_boolean.is_it_night
    to: 'on'
  condition:
    alias: "Modus is configured and bedroom below 22.0"
    and:
      - condition: state
        entity_id: input_boolean.night_airco_on
        state: 'on'
      - condition: numeric_state
        entity_id:
          - sensor.temperatuur_slaapkamer
        above: 21.5
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.overloop
        temperature: 20.0
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.overloop
        hvac_mode: cool
    - service: climate.turn_on
      entity_id: climate.overloop

- alias: Nachtairco modus uit
  trigger:
    platform: state
    entity_id: input_boolean.is_it_night
    to: 'off'
  condition:
    alias: "Modus is configured"
    condition: state
    entity_id: input_boolean.night_airco_on
    state: 'on'
  action:
    - service: climate.turn_off
      entity_id: climate.overloop

